export const SET_AUTHORS = 'SET_AUTHORS';

export const LOGIN_STARTED = 'LOGIN_STARTED';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ENDED = 'LOGIN_ENDED';
export const LOGOUT = 'LOGOUT';

export const LOAD_ARTICLES = 'LOAD_ARTICLES';
export const ADD_ARTICLE = 'ADD_ARTICLE';

export const LOAD_SUBSCRIPTIONS = 'LOAD_SUBSCRIPTIONS';
export const ADD_SUBSCRIPTION = 'ADD_SUBSCRIPTION';
export const REMOVE_SUBSCRIPTION = 'REMOVE_SUBSCRIPTION';

export const ACCEPT_SUBSCRIPTION = 'ACCEPT_SUBSCRIPTION';
export const REJECT_SUBSCRIPTION = 'REJECT_SUBSCRIPTION';
